# Provider Page
twitter_page:  "https://twitter.com/"
facebook_page: "https://www.facebook.com/"
github_page:   "https://github.com/"

# アプリケーション名
app_name: "bokuranoseisaku"

# プログラマTwitterID
programmer_twitter_id: "shu_0115"

# デザイナーTwitterID
designer_twitter_id: "DESIGNER_TWITTER_ID"

# 曜日
weekday: ["日", "月", "火", "水", "木", "金", "土"]

per_page: 30

search_text: "#ぼくらの政策 OR #僕らの政策 OR #ぼくらの福祉政策 OR #ぼくらの都市計画_成長戦略 OR #ぼくらの行政改革 OR #ぼくらの防災_危機管理計画 OR #ぼくらの2020年計画 -rt"